### ISSUE TITLE
No license file available. Can you please add one?

### ISSUE THREAD

**Issue by smunuswami** [abelperezok/DynamoDB-BaseRepository#1]

**Comment by abelperezok** [comment]
Thanks @smunuswami, I'll look into that later today, TBH it's something that slipped through my mind when I set it up

**Comment by abelperezok** [comment]
As requested, license added. 
https://github.com/abelperezok/DynamoDB-BaseRepository/blob/master/LICENSE

**Comment by smunuswami** [comment]
@abelperezok Thanks a lot for your quick response.
